# Dependencies
markdown:         redcarpet
hightlighter:     rouge
github:           [Repository metadata]

# Permalinks
permalink:        pretty

# Setup
title:            Nothing To See
tagline:          There's nothing here worth your time..
url:              http://eddiep.me/blog
paginate:         5
baseurl:          /blog/
author:
  name:           Eddie Penta
  url:            http://eddiep.me
  email:          ecp4224@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/hypereddie/blog
